from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(400, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName('verticalLayout')
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName('listWidget')
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setObjectName('addBtn')
        self.horizontalLayout_2.addWidget(self.addBtn)
        self.editBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editBtn.setObjectName('editBtn')
        self.horizontalLayout_2.addWidget(self.editBtn)
        self.practiceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.practiceBtn.setObjectName('practiceBtn')
        self.horizontalLayout_2.addWidget(self.practiceBtn)
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setObjectName('delBtn')
        self.horizontalLayout_2.addWidget(self.delBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName('textEdit')
        self.verticalLayout.addWidget(self.textEdit)
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setObjectName('exitBtn')
        self.verticalLayout.addWidget(self.exitBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 20))
        self.menubar.setObjectName('menubar')
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName('menuFile')
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName('statusbar')
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName('actionExit')
        self.actionNew_Verse = QtWidgets.QAction(MainWindow)
        self.actionNew_Verse.setObjectName('actionNew_Verse')
        self.menuFile.addAction(self.actionNew_Verse)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'Bible Memorization App'))
        self.addBtn.setText(_translate('MainWindow', 'Add...'))
        self.editBtn.setText(_translate('MainWindow', 'Edit...'))
        self.practiceBtn.setText(_translate('MainWindow', 'Practice...'))
        self.delBtn.setText(_translate('MainWindow', 'Delete'))
        self.textEdit.setHtml(_translate('MainWindow', '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;">\n<p style="-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>'))
        self.exitBtn.setText(_translate('MainWindow', 'Exit'))
        self.menuFile.setTitle(_translate('MainWindow', 'File'))
        self.actionExit.setText(_translate('MainWindow', 'Exit'))
        self.actionNew_Verse.setText(_translate('MainWindow', 'New Verse...'))
# okay decompiling BibleApp.pyc
